// rs-x-cli/templates/react-demo/src/app/app.tsx
import { type FC, useEffect, useState } from 'react';

import { VirtualTableShell } from './virtual-table/virtual-table-shell';

type ThemeMode = 'light' | 'dark';

function getInitialTheme(): ThemeMode {
  const storedTheme = window.localStorage.getItem('rsx-theme');
  if (storedTheme === 'light' || storedTheme === 'dark') {
    return storedTheme;
  }

  return 'dark';
}

export const App: FC = () => {
  const [theme, setTheme] = useState<ThemeMode>(() => getInitialTheme());

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    document.body.setAttribute('data-theme', theme);
    window.localStorage.setItem('rsx-theme', theme);
  }, [theme]);

  return (
    <main className="app-shell">
      <section className="hero">
        <div className="container">
          <div className="heroGrid">
            <div className="heroLeft">
              <p className="app-eyebrow">RS-X React Demo</p>
              <h1 className="hTitle">Virtual Table</h1>
              <p className="hSubhead">
                Million-row scrolling with a fixed RS-X expression pool.
              </p>
              <p className="hSub">
                This demo keeps rendering bounded while streaming pages on
                demand, so scrolling stays smooth without growing expression
                memory with the dataset.
              </p>

              <div className="heroActions">
                <a
                  className="btn btnGhost"
                  href="https://www.rsxjs.com/"
                  target="_blank"
                  rel="noreferrer"
                >
                  rs-x
                </a>
                <button
                  type="button"
                  className="btn btnGhost theme-toggle"
                  aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}
                  onClick={() => {
                    setTheme((currentTheme) =>
                      currentTheme === 'dark' ? 'light' : 'dark',
                    );
                  }}
                >
                  {theme === 'dark' ? 'Light mode' : 'Dark mode'}
                </button>
              </div>
            </div>

            <aside className="card heroNote">
              <h2 className="cardTitle">What This Shows</h2>
              <p className="cardText">
                Only a small row-model pool stays alive while pages stream in
                around the viewport. That means one million logical rows without
                one million live bindings.
              </p>
            </aside>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <section className="app-panel card">
            <VirtualTableShell />
          </section>
        </div>
      </section>
    </main>
  );
};

// rs-x-cli/templates/angular-demo/src/app/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  OnInit,
  inject,
} from '@angular/core';
import { DOCUMENT } from '@angular/common';

import { VirtualTableComponent } from './virtual-table/virtual-table.component';

type ThemeMode = 'light' | 'dark';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [VirtualTableComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  private readonly _document = inject(DOCUMENT);
  @HostBinding('class.theme-dark') public isDarkTheme = false;
  public theme: ThemeMode = 'light';

  public ngOnInit(): void {
    this.theme = this.getInitialTheme();
    this.applyTheme(this.theme);
  }

  public toggleTheme(): void {
    this.theme = this.theme === 'dark' ? 'light' : 'dark';
    this.applyTheme(this.theme);
    window.localStorage.setItem('rsx-theme', this.theme);
  }

  private getInitialTheme(): ThemeMode {
    const storedTheme = window.localStorage.getItem('rsx-theme');
    if (storedTheme === 'light' || storedTheme === 'dark') {
      return storedTheme;
    }

    return 'light';
  }

  private applyTheme(theme: ThemeMode): void {
    this.isDarkTheme = theme === 'dark';
    this._document.documentElement.setAttribute('data-theme', theme);
    this._document.body.setAttribute('data-theme', theme);
  }
}

<main class="app-shell">
  <section class="hero">
    <div class="container">
      <div class="heroGrid">
        <div class="heroLeft">
          <p class="app-eyebrow">RS-X Angular Demo</p>
          <h1 class="hTitle">Virtual Table</h1>
          <p class="hSubhead">Million-row scrolling with a fixed RS-X expression pool.</p>
          <p class="hSub">
            This demo keeps rendering bounded while streaming pages on demand, so
            scrolling stays smooth without growing expression memory with the dataset.
          </p>

          <div class="heroActions">
            <a
              class="btn btnGhost"
              href="https://www.rsxjs.com/"
              target="_blank"
              rel="noreferrer"
            >
              rs-x
            </a>
            <button
              type="button"
              class="btn btnGhost theme-toggle"
              (click)="toggleTheme()"
              [attr.aria-label]="'Switch to ' + (theme === 'dark' ? 'light' : 'dark') + ' mode'"
            >
              {{ theme === 'dark' ? 'Light mode' : 'Dark mode' }}
            </button>
          </div>
        </div>

        <aside class="card heroNote">
          <h2 class="cardTitle">What This Shows</h2>
          <p class="cardText">
            Only a small row-model pool stays alive while pages stream in around the
            viewport. That means one million logical rows without one million live
            bindings.
          </p>
        </aside>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <section class="app-panel card">
        <rsx-virtual-table></rsx-virtual-table>
      </section>
    </div>
  </section>
</main>
