// rs-x-cli/templates/react-demo/src/app/app.tsx
import { type FC, useEffect, useState } from 'react';

import { VirtualTableShell } from './virtual-table/virtual-table-shell';

type ThemeMode = 'light' | 'dark';

function getInitialTheme(): ThemeMode {
  const storedTheme = window.localStorage.getItem('rsx-theme');
  if (storedTheme === 'light' || storedTheme === 'dark') {
    return storedTheme;
  }

  return 'dark';
}

export const App: FC = () => {
  const [theme, setTheme] = useState<ThemeMode>(() => getInitialTheme());

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    document.body.setAttribute('data-theme', theme);
    window.localStorage.setItem('rsx-theme', theme);
  }, [theme]);

  return (
    <main className="app-shell">
      <section className="hero">
        <div className="container">
          <div className="heroGrid">
            <div className="heroLeft">
              <p className="app-eyebrow">RS-X React Demo</p>
              <h1 className="hTitle">Virtual Table</h1>
              <p className="hSubhead">
                Million-row scrolling with a fixed RS-X expression pool.
              </p>
              <p className="hSub">
                This demo keeps rendering bounded while streaming pages on
                demand, so scrolling stays smooth without growing expression
                memory with the dataset.
              </p>

              <div className="heroActions">
                <a
                  className="btn btnGhost"
                  href="https://www.rsxjs.com/"
                  target="_blank"
                  rel="noreferrer"
                >
                  rs-x
                </a>
                <button
                  type="button"
                  className="btn btnGhost theme-toggle"
                  aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}
                  onClick={() => {
                    setTheme((currentTheme) =>
                      currentTheme === 'dark' ? 'light' : 'dark',
                    );
                  }}
                >
                  {theme === 'dark' ? 'Light mode' : 'Dark mode'}
                </button>
              </div>
            </div>

            <aside className="card heroNote">
              <h2 className="cardTitle">What This Shows</h2>
              <p className="cardText">
                Only a small row-model pool stays alive while pages stream in
                around the viewport. That means one million logical rows without
                one million live bindings.
              </p>
            </aside>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <section className="app-panel card">
            <VirtualTableShell />
          </section>
        </div>
      </section>
    </main>
  );
};

// rs-x-cli/templates/vue-demo/src/App.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';

import VirtualTableShell from './components/VirtualTableShell.vue';

type ThemeMode = 'light' | 'dark';

const theme = ref<ThemeMode>('dark');

onMounted(() => {
  const storedTheme = window.localStorage.getItem('rsx-theme');
  if (storedTheme === 'light' || storedTheme === 'dark') {
    theme.value = storedTheme;
  }
});

watch(
  theme,
  (nextTheme) => {
    document.documentElement.setAttribute('data-theme', nextTheme);
    document.body.setAttribute('data-theme', nextTheme);
    window.localStorage.setItem('rsx-theme', nextTheme);
  },
  { immediate: true },
);

function toggleTheme(): void {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
}
</script>

<template>
  <main class="app-shell">
    <section class="hero">
      <div class="container">
        <div class="heroGrid">
          <div class="heroLeft">
            <p class="app-eyebrow">RS-X Vue Demo</p>
            <h1 class="hTitle">Virtual Table</h1>
            <p class="hSubhead">
              Million-row scrolling with a fixed RS-X expression pool.
            </p>
            <p class="hSub">
              This demo keeps rendering bounded while streaming pages on demand,
              so scrolling stays smooth without growing expression memory with the
              dataset.
            </p>

            <div class="heroActions">
              <a
                class="btn btnGhost"
                href="https://www.rsxjs.com/"
                target="_blank"
                rel="noreferrer"
              >
                rs-x
              </a>
              <button
                type="button"
                class="btn btnGhost theme-toggle"
                :aria-label="`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`"
                @click="toggleTheme"
              >
                {{ theme === 'dark' ? 'Light mode' : 'Dark mode' }}
              </button>
            </div>
          </div>

          <aside class="card heroNote">
            <h2 class="cardTitle">What This Shows</h2>
            <p class="cardText">
              Only a small row-model pool stays alive while pages stream in around
              the viewport. That means one million logical rows without one million
              live bindings.
            </p>
          </aside>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <section class="app-panel card">
          <VirtualTableShell />
        </section>
      </div>
    </section>
  </main>
</template>
